/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.layerd.view;

/**
 *
 * @author ASUS
 */
public class LayoutView extends javax.swing.JFrame {

    /**
     * Creates new form LayoutView
     */
    public LayoutView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        sideNAVPanel = new javax.swing.JPanel();
        manageCarCategoriesButton = new javax.swing.JButton();
        manageCarsButton = new javax.swing.JButton();
        manageCustomersButton = new javax.swing.JButton();
        manageUsersButton = new javax.swing.JButton();
        newRentalButton = new javax.swing.JButton();
        returnCarButton = new javax.swing.JButton();
        overdueRentalsButton = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(0, 153, 153));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Cars for Rent");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sideNAVPanel.setBackground(new java.awt.Color(102, 255, 204));

        manageCarCategoriesButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageCarCategoriesButton.setText("Manage Car Categories");
        manageCarCategoriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCarCategoriesButtonActionPerformed(evt);
            }
        });

        manageCarsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageCarsButton.setText("Manage Cars");
        manageCarsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCarsButtonActionPerformed(evt);
            }
        });

        manageCustomersButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageCustomersButton.setText("Manage Customers");
        manageCustomersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomersButtonActionPerformed(evt);
            }
        });

        manageUsersButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageUsersButton.setText("Manage Users");
        manageUsersButton.setToolTipText("");
        manageUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersButtonActionPerformed(evt);
            }
        });

        newRentalButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newRentalButton.setText("New Rental");
        newRentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRentalButtonActionPerformed(evt);
            }
        });

        returnCarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnCarButton.setText("Return Car");
        returnCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCarButtonActionPerformed(evt);
            }
        });

        overdueRentalsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        overdueRentalsButton.setText("Overdue Rentals");
        overdueRentalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overdueRentalsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideNAVPanelLayout = new javax.swing.GroupLayout(sideNAVPanel);
        sideNAVPanel.setLayout(sideNAVPanelLayout);
        sideNAVPanelLayout.setHorizontalGroup(
            sideNAVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideNAVPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideNAVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageCarCategoriesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageCarsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageCustomersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageUsersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newRentalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overdueRentalsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideNAVPanelLayout.setVerticalGroup(
            sideNAVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideNAVPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageCarCategoriesButton)
                .addGap(26, 26, 26)
                .addComponent(manageCarsButton)
                .addGap(26, 26, 26)
                .addComponent(manageCustomersButton)
                .addGap(26, 26, 26)
                .addComponent(manageUsersButton)
                .addGap(26, 26, 26)
                .addComponent(newRentalButton)
                .addGap(26, 26, 26)
                .addComponent(returnCarButton)
                .addGap(26, 26, 26)
                .addComponent(overdueRentalsButton)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideNAVPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sideNAVPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageCarCategoriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCarCategoriesButtonActionPerformed
        loadManageCarCategoriesPanel();
    }//GEN-LAST:event_manageCarCategoriesButtonActionPerformed

    private void manageCarsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCarsButtonActionPerformed
        LoadManageCarsPanel();
    }//GEN-LAST:event_manageCarsButtonActionPerformed

    private void manageCustomersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomersButtonActionPerformed
        LoadManageCustomersPanel();
    }//GEN-LAST:event_manageCustomersButtonActionPerformed

    private void manageUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersButtonActionPerformed
        LoadUsersManagementPanel();
    }//GEN-LAST:event_manageUsersButtonActionPerformed

    private void newRentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRentalButtonActionPerformed
        LoadNewRentalPanel();
    }//GEN-LAST:event_newRentalButtonActionPerformed

    private void returnCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnCarButtonActionPerformed
        LoadReturnCarPanel();
    }//GEN-LAST:event_returnCarButtonActionPerformed

    private void overdueRentalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overdueRentalsButtonActionPerformed
        LoadOverdueRentalsPanel();
    }//GEN-LAST:event_overdueRentalsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton manageCarCategoriesButton;
    private javax.swing.JButton manageCarsButton;
    private javax.swing.JButton manageCustomersButton;
    private javax.swing.JButton manageUsersButton;
    private javax.swing.JButton newRentalButton;
    private javax.swing.JButton overdueRentalsButton;
    private javax.swing.JButton returnCarButton;
    private javax.swing.JPanel sideNAVPanel;
    // End of variables declaration//GEN-END:variables

    private void loadManageCarCategoriesPanel() {
        bodyPanel.removeAll();
        ManageCarCategoriesPanel manageCarCategoriesPanel =new ManageCarCategoriesPanel();
        manageCarCategoriesPanel.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
        bodyPanel.add(manageCarCategoriesPanel);
        bodyPanel.repaint();
        bodyPanel.revalidate();
        
        
    }

    private void LoadManageCarsPanel() {
        bodyPanel.removeAll();
        ManageCarsPanel manageCarsPanel =new ManageCarsPanel();
        manageCarsPanel.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
        bodyPanel.add(manageCarsPanel);
        bodyPanel.repaint();
        bodyPanel.revalidate();
    }

    private void LoadManageCustomersPanel() {
        bodyPanel.removeAll();
        ManageCustomersPanel manageCustomersPanel =new ManageCustomersPanel();
        manageCustomersPanel.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
        bodyPanel.add(manageCustomersPanel);
        bodyPanel.repaint();
        bodyPanel.revalidate();
    }

    private void LoadUsersManagementPanel() {
        bodyPanel.removeAll();
        UsersManagementPanel usersManagementPanel =new UsersManagementPanel();
        usersManagementPanel.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
        bodyPanel.add(usersManagementPanel);
        bodyPanel.repaint();
        bodyPanel.revalidate();
    }

    private void LoadNewRentalPanel() {
         bodyPanel.removeAll();
        NewRentalPanel newRentalPanel =new NewRentalPanel();
        newRentalPanel.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
        bodyPanel.add(newRentalPanel);
        bodyPanel.repaint();
        bodyPanel.revalidate();
    }

    private void LoadReturnCarPanel() {
        bodyPanel.removeAll();
        ReturnCarPanel returnCarPanel =new ReturnCarPanel();
        returnCarPanel.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
        bodyPanel.add(returnCarPanel);
        bodyPanel.repaint();
        bodyPanel.revalidate();
    }

    private void LoadOverdueRentalsPanel() {
         bodyPanel.removeAll();
        OverdueRentalsPanel overdueRentalsPanel =new OverdueRentalsPanel();
        overdueRentalsPanel.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
        bodyPanel.add(overdueRentalsPanel);
        bodyPanel.repaint();
        bodyPanel.revalidate();
    }
}
