/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.layerd.view;

/**
 *
 * @author ASUS
 */
public class ManageCustomersPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomersPanel
     */
    public ManageCustomersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageCustomersHeaderPanel = new javax.swing.JPanel();
        manageCustomersHeaderLabel = new javax.swing.JLabel();
        manageCustomersTopPanel = new javax.swing.JPanel();
        manageCustomersBottomPanel = new javax.swing.JPanel();

        manageCustomersHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageCustomersHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageCustomersHeaderLabel.setText("Manage Customers");

        javax.swing.GroupLayout manageCustomersHeaderPanelLayout = new javax.swing.GroupLayout(manageCustomersHeaderPanel);
        manageCustomersHeaderPanel.setLayout(manageCustomersHeaderPanelLayout);
        manageCustomersHeaderPanelLayout.setHorizontalGroup(
            manageCustomersHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCustomersHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        manageCustomersHeaderPanelLayout.setVerticalGroup(
            manageCustomersHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCustomersHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageCustomersTopPanelLayout = new javax.swing.GroupLayout(manageCustomersTopPanel);
        manageCustomersTopPanel.setLayout(manageCustomersTopPanelLayout);
        manageCustomersTopPanelLayout.setHorizontalGroup(
            manageCustomersTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageCustomersTopPanelLayout.setVerticalGroup(
            manageCustomersTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageCustomersBottomPanelLayout = new javax.swing.GroupLayout(manageCustomersBottomPanel);
        manageCustomersBottomPanel.setLayout(manageCustomersBottomPanelLayout);
        manageCustomersBottomPanelLayout.setHorizontalGroup(
            manageCustomersBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageCustomersBottomPanelLayout.setVerticalGroup(
            manageCustomersBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCustomersHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageCustomersTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageCustomersBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageCustomersHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageCustomersTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageCustomersBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel manageCustomersBottomPanel;
    private javax.swing.JLabel manageCustomersHeaderLabel;
    private javax.swing.JPanel manageCustomersHeaderPanel;
    private javax.swing.JPanel manageCustomersTopPanel;
    // End of variables declaration//GEN-END:variables
}
