/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.layerd.view;

/**
 *
 * @author ASUS
 */
public class ManageCarsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCarsPanel
     */
    public ManageCarsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageCarsHeaderPanel = new javax.swing.JPanel();
        manageCarsHeaderLabel = new javax.swing.JLabel();
        manageCarsTopPanel = new javax.swing.JPanel();
        manageCarsBottomPanel = new javax.swing.JPanel();

        manageCarsHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageCarsHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageCarsHeaderLabel.setText("Manage Cars");

        javax.swing.GroupLayout manageCarsHeaderPanelLayout = new javax.swing.GroupLayout(manageCarsHeaderPanel);
        manageCarsHeaderPanel.setLayout(manageCarsHeaderPanelLayout);
        manageCarsHeaderPanelLayout.setHorizontalGroup(
            manageCarsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCarsHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        manageCarsHeaderPanelLayout.setVerticalGroup(
            manageCarsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCarsHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageCarsTopPanelLayout = new javax.swing.GroupLayout(manageCarsTopPanel);
        manageCarsTopPanel.setLayout(manageCarsTopPanelLayout);
        manageCarsTopPanelLayout.setHorizontalGroup(
            manageCarsTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageCarsTopPanelLayout.setVerticalGroup(
            manageCarsTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageCarsBottomPanelLayout = new javax.swing.GroupLayout(manageCarsBottomPanel);
        manageCarsBottomPanel.setLayout(manageCarsBottomPanelLayout);
        manageCarsBottomPanelLayout.setHorizontalGroup(
            manageCarsBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageCarsBottomPanelLayout.setVerticalGroup(
            manageCarsBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCarsHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageCarsTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageCarsBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageCarsHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageCarsTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageCarsBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel manageCarsBottomPanel;
    private javax.swing.JLabel manageCarsHeaderLabel;
    private javax.swing.JPanel manageCarsHeaderPanel;
    private javax.swing.JPanel manageCarsTopPanel;
    // End of variables declaration//GEN-END:variables
}
