/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.layerd.view;

/**
 *
 * @author ASUS
 */
public class NewRentalPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewRentalPanel
     */
    public NewRentalPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageRentalsHeaderPanel = new javax.swing.JPanel();
        manageRentalsHeaderLabel = new javax.swing.JLabel();
        manageRentalsTopPanel = new javax.swing.JPanel();
        manageRentalsBottomPanel = new javax.swing.JPanel();

        manageRentalsHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageRentalsHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageRentalsHeaderLabel.setText("Manage Rentals");

        javax.swing.GroupLayout manageRentalsHeaderPanelLayout = new javax.swing.GroupLayout(manageRentalsHeaderPanel);
        manageRentalsHeaderPanel.setLayout(manageRentalsHeaderPanelLayout);
        manageRentalsHeaderPanelLayout.setHorizontalGroup(
            manageRentalsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageRentalsHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        manageRentalsHeaderPanelLayout.setVerticalGroup(
            manageRentalsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageRentalsHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageRentalsTopPanelLayout = new javax.swing.GroupLayout(manageRentalsTopPanel);
        manageRentalsTopPanel.setLayout(manageRentalsTopPanelLayout);
        manageRentalsTopPanelLayout.setHorizontalGroup(
            manageRentalsTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageRentalsTopPanelLayout.setVerticalGroup(
            manageRentalsTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageRentalsBottomPanelLayout = new javax.swing.GroupLayout(manageRentalsBottomPanel);
        manageRentalsBottomPanel.setLayout(manageRentalsBottomPanelLayout);
        manageRentalsBottomPanelLayout.setHorizontalGroup(
            manageRentalsBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageRentalsBottomPanelLayout.setVerticalGroup(
            manageRentalsBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageRentalsHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageRentalsTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageRentalsBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageRentalsHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageRentalsTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageRentalsBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel manageRentalsBottomPanel;
    private javax.swing.JLabel manageRentalsHeaderLabel;
    private javax.swing.JPanel manageRentalsHeaderPanel;
    private javax.swing.JPanel manageRentalsTopPanel;
    // End of variables declaration//GEN-END:variables
}
