/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.layerd.view;

/**
 *
 * @author ASUS
 */
public class OverdueRentalsPanel extends javax.swing.JPanel {

    /**
     * Creates new form OverdueRentalsPanel
     */
    public OverdueRentalsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageOverdueRentalsHeaderPanel = new javax.swing.JPanel();
        manageOverdueRentalsHeaderLabel = new javax.swing.JLabel();
        manageOverdueRentalsTopPanel = new javax.swing.JPanel();
        manageOverdueRentalsBottomPanel = new javax.swing.JPanel();

        manageOverdueRentalsHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageOverdueRentalsHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageOverdueRentalsHeaderLabel.setText("Manage Overdue Rentals");

        javax.swing.GroupLayout manageOverdueRentalsHeaderPanelLayout = new javax.swing.GroupLayout(manageOverdueRentalsHeaderPanel);
        manageOverdueRentalsHeaderPanel.setLayout(manageOverdueRentalsHeaderPanelLayout);
        manageOverdueRentalsHeaderPanelLayout.setHorizontalGroup(
            manageOverdueRentalsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageOverdueRentalsHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        manageOverdueRentalsHeaderPanelLayout.setVerticalGroup(
            manageOverdueRentalsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageOverdueRentalsHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageOverdueRentalsTopPanelLayout = new javax.swing.GroupLayout(manageOverdueRentalsTopPanel);
        manageOverdueRentalsTopPanel.setLayout(manageOverdueRentalsTopPanelLayout);
        manageOverdueRentalsTopPanelLayout.setHorizontalGroup(
            manageOverdueRentalsTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageOverdueRentalsTopPanelLayout.setVerticalGroup(
            manageOverdueRentalsTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageOverdueRentalsBottomPanelLayout = new javax.swing.GroupLayout(manageOverdueRentalsBottomPanel);
        manageOverdueRentalsBottomPanel.setLayout(manageOverdueRentalsBottomPanelLayout);
        manageOverdueRentalsBottomPanelLayout.setHorizontalGroup(
            manageOverdueRentalsBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageOverdueRentalsBottomPanelLayout.setVerticalGroup(
            manageOverdueRentalsBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageOverdueRentalsHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageOverdueRentalsTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageOverdueRentalsBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageOverdueRentalsHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageOverdueRentalsTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageOverdueRentalsBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel manageOverdueRentalsBottomPanel;
    private javax.swing.JLabel manageOverdueRentalsHeaderLabel;
    private javax.swing.JPanel manageOverdueRentalsHeaderPanel;
    private javax.swing.JPanel manageOverdueRentalsTopPanel;
    // End of variables declaration//GEN-END:variables
}
