/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.layerd.view;

/**
 *
 * @author ASUS
 */
public class ReturnCarPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReturnCarPanel
     */
    public ReturnCarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageCarReturnHeaderPanel = new javax.swing.JPanel();
        manageCarReturnHeaderLabel = new javax.swing.JLabel();
        manageCarReturnTopPanel = new javax.swing.JPanel();
        manageCarReturnBottomPanel = new javax.swing.JPanel();

        manageCarReturnHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageCarReturnHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageCarReturnHeaderLabel.setText("Manage Car Return");

        javax.swing.GroupLayout manageCarReturnHeaderPanelLayout = new javax.swing.GroupLayout(manageCarReturnHeaderPanel);
        manageCarReturnHeaderPanel.setLayout(manageCarReturnHeaderPanelLayout);
        manageCarReturnHeaderPanelLayout.setHorizontalGroup(
            manageCarReturnHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCarReturnHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        manageCarReturnHeaderPanelLayout.setVerticalGroup(
            manageCarReturnHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCarReturnHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageCarReturnTopPanelLayout = new javax.swing.GroupLayout(manageCarReturnTopPanel);
        manageCarReturnTopPanel.setLayout(manageCarReturnTopPanelLayout);
        manageCarReturnTopPanelLayout.setHorizontalGroup(
            manageCarReturnTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageCarReturnTopPanelLayout.setVerticalGroup(
            manageCarReturnTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageCarReturnBottomPanelLayout = new javax.swing.GroupLayout(manageCarReturnBottomPanel);
        manageCarReturnBottomPanel.setLayout(manageCarReturnBottomPanelLayout);
        manageCarReturnBottomPanelLayout.setHorizontalGroup(
            manageCarReturnBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageCarReturnBottomPanelLayout.setVerticalGroup(
            manageCarReturnBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageCarReturnHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageCarReturnTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageCarReturnBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageCarReturnHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageCarReturnTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageCarReturnBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel manageCarReturnBottomPanel;
    private javax.swing.JLabel manageCarReturnHeaderLabel;
    private javax.swing.JPanel manageCarReturnHeaderPanel;
    private javax.swing.JPanel manageCarReturnTopPanel;
    // End of variables declaration//GEN-END:variables
}
