/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.layerd.view;

/**
 *
 * @author ASUS
 */
public class UsersManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListRentalsPanel
     */
    public UsersManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageUsersHeaderPanel = new javax.swing.JPanel();
        manageUsersHeaderLabel = new javax.swing.JLabel();
        manageUsersTopPanel = new javax.swing.JPanel();
        manageUsersBottomPanel = new javax.swing.JPanel();

        manageUsersHeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageUsersHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageUsersHeaderLabel.setText("Manage Users");

        javax.swing.GroupLayout manageUsersHeaderPanelLayout = new javax.swing.GroupLayout(manageUsersHeaderPanel);
        manageUsersHeaderPanel.setLayout(manageUsersHeaderPanelLayout);
        manageUsersHeaderPanelLayout.setHorizontalGroup(
            manageUsersHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageUsersHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        manageUsersHeaderPanelLayout.setVerticalGroup(
            manageUsersHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageUsersHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageUsersTopPanelLayout = new javax.swing.GroupLayout(manageUsersTopPanel);
        manageUsersTopPanel.setLayout(manageUsersTopPanelLayout);
        manageUsersTopPanelLayout.setHorizontalGroup(
            manageUsersTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageUsersTopPanelLayout.setVerticalGroup(
            manageUsersTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout manageUsersBottomPanelLayout = new javax.swing.GroupLayout(manageUsersBottomPanel);
        manageUsersBottomPanel.setLayout(manageUsersBottomPanelLayout);
        manageUsersBottomPanelLayout.setHorizontalGroup(
            manageUsersBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        manageUsersBottomPanelLayout.setVerticalGroup(
            manageUsersBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageUsersHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageUsersTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageUsersBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageUsersHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageUsersTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageUsersBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel manageUsersBottomPanel;
    private javax.swing.JLabel manageUsersHeaderLabel;
    private javax.swing.JPanel manageUsersHeaderPanel;
    private javax.swing.JPanel manageUsersTopPanel;
    // End of variables declaration//GEN-END:variables
}
